- name: add DataStax Yum repo
  yum_repository:
    name: datastax
    description: DataStax Repository
    baseurl: https://{{ dsa_email_address }}:{{ dsa_password }}@rpm.datastax.com/enterprise
    gpgcheck: no

- name: install opscenter
  yum: name=opscenter

- name: put opscenterd.conf
  template: src=opscenterd.conf dest=/etc/opscenter/opscenterd.conf
  register: opscenter_conf

- name: start or restart opscenterd
  service: name=opscenterd enabled=yes state={{ 'restarted' if opscenter_conf.changed else 'started' }}
